<!-- Copyright (c) 2026 Specter contributors. Licensed under AGPL-3.0-only. -->
<!--
  Chat-files shortcut popover.

  Surfaces every document seen by the current chat — uploaded by the
  user, generated by a tool (today docx/xlsx from generate_docx),
  rejected via the accept/reject flow — in a single list so the user
  can find a generated docx after the chat scrolled past, or jump back
  to a document they vetoed. Click a row to open it in the existing
  doc-viewer side panel (same as the ChatSteps doc card).

  Source of truth: `GET /chat/:id/documents`. The backend enumerates
  every doc the chat has touched across five categories — uploaded
  attachments, tool-generated docs, rejected docs (origin preserved),
  project-inherited docs and KB/corpora docs cited by the assistant —
  and returns the origin tag + decision state on each row so the
  popover paints without a per-doc fan-out.
-->
<script lang="ts">
  import { docViewer } from '$lib/stores/doc-viewer.svelte'
  import { chatStore } from '$lib/stores/chat.svelte'
  import { chatApi } from '$lib/api/chat'
  import { i18n } from '$lib/stores/i18n.svelte'
  import { fileIconColor } from '$lib/utils/file-icon'
  import Spinner from '$lib/components/ui/Spinner.svelte'
  import { FileText, X } from 'lucide-svelte'

  interface Props {
    open: boolean
    onclose?: () => void
  }

  let { open = $bindable(false), onclose }: Props = $props()

  type Origin = 'uploaded' | 'generated' | 'project' | 'referenced'
  type Decision = 'accepted' | 'rejected'

  interface Row {
    docId: string
    filename: string
    origin: Origin
    decision: Decision
  }

  let rows = $state<Row[]>([])
  let loading = $state(false)

  // Re-fetch the chat's documents every time the panel opens. The set
  // (new generate / upload / project doc), the citations referenced
  // (new turn cites a different KB doc) and the decision state can all
  // change between opens, and the backend bundles everything in one
  // SELECT — cheap enough to re-run without caching.
  $effect(() => {
    if (!open) return
    const chatId = chatStore.activeId
    if (!chatId) {
      // Brand-new unsaved chat: nothing exists server-side yet.
      rows = []
      return
    }
    loading = true
    chatApi
      .documents(chatId)
      .then((res) => {
        if (!open) return // raced a close
        rows = res.documents.map((d) => ({
          docId: d.id,
          filename: d.filename,
          origin: d.origin,
          decision: d.decision,
        }))
      })
      .catch(() => {
        if (open) rows = []
      })
      .finally(() => {
        loading = false
      })
  })

  function close() {
    open = false
    onclose?.()
  }

  function pick(r: Row) {
    docViewer.openDocument(r.docId, r.filename)
    close()
  }

  function originLabel(o: Origin): string {
    switch (o) {
      case 'uploaded':
        return i18n.t('ChatFiles.originUploaded')
      case 'generated':
        return i18n.t('ChatFiles.originGenerated')
      case 'project':
        return i18n.t('ChatFiles.originProject')
      case 'referenced':
        return i18n.t('ChatFiles.originReferenced')
    }
  }

  /** Tag chip palette per origin. Generated keeps the brand accent it
   *  had in v0.4.3; uploaded stays neutral; project gets a calm
   *  secondary tint; referenced uses the info colour so cited KB docs
   *  feel distinct from owned uploads. */
  function originChip(o: Origin): string {
    switch (o) {
      case 'generated':
        return 'bg-(--color-brand-50) text-(--color-brand-700)'
      case 'project':
        return 'bg-(--color-success-50) text-(--color-success-700)'
      case 'referenced':
        return 'bg-(--color-info-50) text-(--color-info-700)'
      default:
        return 'bg-(--color-surface-100) text-(--color-text-secondary)'
    }
  }
</script>

{#if open}
  <!-- Backdrop closes the popover, but it stays transparent — this is
       a lightweight pop-up anchored above the composer, not a modal. -->
  <!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
  <div class="fixed inset-0 z-30" onclick={close}></div>

  <div
    class="absolute bottom-full mb-1.5 left-0 z-40
           w-[min(28rem,calc(100vw-3rem))] max-h-[60vh]
           rounded-(--radius-md) border border-(--color-surface-200)
           bg-(--color-surface-0) shadow-(--shadow-modal)
           flex flex-col overflow-hidden"
    role="dialog"
    aria-label={i18n.t('ChatFiles.title')}
  >
    <header
      class="px-3.5 py-2.5 border-b border-(--color-surface-100)
             flex items-center justify-between gap-3 shrink-0"
    >
      <h2 class="text-sm font-semibold text-(--color-text-primary)">
        {i18n.t('ChatFiles.title')}
      </h2>
      <button
        type="button"
        aria-label={i18n.t('Common.close')}
        onclick={close}
        class="inline-flex h-6 w-6 items-center justify-center rounded-(--radius-md)
               text-(--color-text-secondary) hover:bg-(--color-hover-bg)"
      >
        <X size={14} />
      </button>
    </header>

    <div class="overflow-y-auto flex-1 min-h-0">
      {#if rows.length === 0}
        <p class="px-3.5 py-6 text-xs text-(--color-text-secondary) text-center">
          {i18n.t('ChatFiles.empty')}
        </p>
      {:else}
        <ul class="py-1">
          {#each rows as r (r.docId)}
            {@const isRejected = r.decision === 'rejected'}
            <li>
              <button
                type="button"
                onclick={() => pick(r)}
                class="w-full flex items-center gap-2.5 px-3.5 py-2 text-left
                       hover:bg-(--color-hover-bg) focus:outline-none
                       focus-visible:bg-(--color-hover-bg)"
              >
                <FileText size={16} class="{fileIconColor(r.filename)} shrink-0" />
                <span
                  class="flex-1 min-w-0 truncate text-sm
                         text-(--color-text-primary)
                         {isRejected ? 'line-through text-(--color-text-secondary)' : ''}"
                  title={r.filename}
                >
                  {r.filename}
                </span>
                <span
                  class="text-[10px] uppercase tracking-wide px-1.5 py-0.5 rounded-(--radius-sm) {originChip(
                    r.origin,
                  )}"
                >
                  {originLabel(r.origin)}
                </span>
                {#if isRejected}
                  <span
                    class="text-[10px] uppercase tracking-wide px-1.5 py-0.5 rounded-(--radius-sm)
                           bg-(--color-danger-500) text-white"
                  >
                    {i18n.t('DocViewer.decision.rejectedBadge')}
                  </span>
                {/if}
              </button>
            </li>
          {/each}
        </ul>
      {/if}
    </div>

    {#if loading}
      <footer
        class="px-3.5 py-2 border-t border-(--color-surface-100)
               text-[11px] text-(--color-text-secondary)
               flex items-center gap-2 shrink-0"
      >
        <Spinner size="sm" />
        <span>{i18n.t('ChatFiles.hydrating')}</span>
      </footer>
    {/if}
  </div>
{/if}
